CREATE TABLE HISTORY(
  ENTRY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME  VARCHAR(16) NOT NULL,
  SEARCH_DATE DATE,
  TYPE VARCHAR(16) NOT NULL
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TYPE VARCHAR(16) NOT NULL,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  EMAIL_ADRESS VARCHAR(64) NOT NULL,
  USER_ACCOUNT VARCHAR(16) NOT NULL,
  USER_PASSWORD VARCHAR(128) NOT NULL,
  CREATE_DATE DATE NOT NULL,
  ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE LOGIN(
  LOGIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOGIN_NAME VARCHAR(64) NOT NULL,
  USER_ACCOUNT VARCHAR(16) NOT NULL,
  USER_PASSWORD VARCHAR(128) NOT NULL
)